<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\System\Department;
use App\Models\Membership\Member;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class DepartmentController extends Controller
{
    public function index(Request $request)
    {
        $search = $request->input('search');

        $activeDepartmentsQuery = Department::withCount('members')->where('status', 'active');
        $archivedDepartmentsQuery = Department::withCount('members')->where('status', 'archived');

        if ($search) {
            $activeDepartmentsQuery->where(function ($q) use ($search) {
                $q->where('name', 'like', "%{$search}%")
                  ->orWhere('code', 'like', "%{$search}%");
            });
            $archivedDepartmentsQuery->where(function ($q) use ($search) {
                $q->where('name', 'like', "%{$search}%")
                  ->orWhere('code', 'like', "%{$search}%");
            });
        }

        $activeDepartments = $activeDepartmentsQuery->orderBy('created_at', 'desc')->paginate(10, ['*'], 'active_page');
        $archivedDepartments = $archivedDepartmentsQuery->orderBy('created_at', 'desc')->paginate(10, ['*'], 'archived_page');

        // We use a single query to calculate the counts for both active and archived departments to improve performance.
        $departmentCounts = Department::selectRaw('
            SUM(CASE WHEN status = "active" THEN 1 ELSE 0 END) as total_active,
            SUM(CASE WHEN status = "archived" THEN 1 ELSE 0 END) as total_archived
        ')->first();

        $totalActive = $departmentCounts->total_active ?? 0;
        $totalArchived = $departmentCounts->total_archived ?? 0;

        // We cache the total member count to prevent querying a large table on every request, which improves page load times.
        $totalMembers = Cache::remember('total_members_count', 3600, function () {
            return Member::count();
        });

        return view('admin.departments.index', compact('activeDepartments', 'archivedDepartments', 'totalActive', 'totalArchived', 'totalMembers', 'search'));
    }

    public function show(Request $request, Department $department)
    {
        $search = $request->input('search');
        $status = $request->input('status');

        $membersQuery = $department->members()->with('membershipInfo');

        if ($search) {
            $membersQuery->where(function($q) use ($search) {
                $q->where('full_name', 'like', "%{$search}%")
                  ->orWhere('national_id', 'like', "%{$search}%")
                  ->orWhereHas('membershipInfo', function($q2) use ($search) {
                      $q2->where('membership_number', 'like', "%{$search}%");
                  });
            });
        }

        if ($status && $status !== 'الكل') {
            $statusMap = [
                'نشط' => 'active',
                'قيد التسجيل' => 'pending_registration',
                'إعارة' => 'loaned',
                'محال للمعاش' => 'pension_eligible',
                'منسحب' => 'withdrawn',
                'مفصول' => 'dismissed',
                'أجازه بدون مرتب' => 'unpaid_leave',
                'منتهية العضوية' => 'membership_expired',
                'موقوف' => 'suspended'
            ];
            $mappedStatus = $statusMap[$status] ?? null;
            if ($mappedStatus) {
                $membersQuery->whereHas('membershipInfo', function($q) use ($mappedStatus) {
                    $q->where('status', $mappedStatus);
                });
            }
        }

        $members = $membersQuery->orderBy('created_at', 'desc')->paginate(10);

        return view('admin.departments.show', compact('department', 'members', 'search', 'status'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            // The code can either be provided by the user or auto-generated by the system.
        ]);

        $code = $request->input('code');
        if (!$code) {
            // If no code was provided, automatically generate a unique code (e.g., DEP-1A2B).
            $code = 'DEP-' . strtoupper(substr(uniqid(), -4));
        }

        Department::create([
            'name' => $request->name,
            'code' => $code,
            'status' => 'active',
        ]);

        return redirect()->route('admin.departments.index')->with('success', 'تم إضافة الكلية بنجاح');
    }

    public function update(Request $request, Department $department)
    {
        $request->validate([
            'name' => 'required|string|max:255',
        ]);

        $department->update([
            'name' => $request->name,
        ]);

        return redirect()->route('admin.departments.index')->with('success', 'تم تعديل بيانات الكلية بنجاح');
    }

    public function archive(Department $department)
    {
        $department->update(['status' => 'archived']);
        return redirect()->route('admin.departments.index')->with('success', 'تم أرشفة الكلية بنجاح');
    }

    public function restore(Department $department)
    {
        $department->update(['status' => 'active']);
        return redirect()->route('admin.departments.index')->with('success', 'تم استعادة الكلية بنجاح');
    }
}
